### PR TITLE
add canonical link option

### PR DESCRIPTION
**Pull request by tostasqb**
https://moz.com/learn/seo/canonicalization

### CODE REVIEW

**Comment by tostasqb** [comment]
@owen2345 if you can check this out. It's a little/quick improvement

**Comment by texpert** [comment]
Yes, @owen2345 , this should be useful. Could you have a look at the PR, please?

**Comment by texpert** [comment]
Thanks, @owen2345 !

Could you, also, cut a cama_meta_tag gem release, please?

**Comment by owen2345** [comment]
Done: 1.7.2

**Pull request merged**
